<?php

namespace AEMR\Bundle\MarketResearchBundle\Repository;

use AEMR\Bundle\MarketResearchBundle\Repository\AEMREntityRepository AS  EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{


}
