<?php

namespace AEMR\Bundle\MarketResearchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GeoCustomIndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCustomIndicatorRepository extends EntityRepository
{
}
