<?php

namespace AEMR\Bundle\MarketResearchBundle\Repository;

use AEMR\Bundle\MarketResearchBundle\Repository\AEMREntityRepository AS  EntityRepository;

/**
 * GeographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographyRepository extends EntityRepository
{
}
