#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

use AEMR\Bundle\MarketResearchBundle\Command\LoadCsvCommand;
use AEMR\Bundle\MarketResearchBundle\Command\LoadGeoGroupCommand;
use AEMR\Bundle\MarketResearchBundle\Command\LoadWDIDataCommand;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);


$loadCsv = new LoadCsvCommand();
$application->add($loadCsv);

$loadGeoGroupCommand = new LoadGeoGroupCommand();
$application->add($loadGeoGroupCommand);

$loadWDIDataCommand = new LoadWDIDataCommand();
$application->add($loadWDIDataCommand);

$application->run($input);
